# Generated by Django 5.1.3 on 2024-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncdc', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hod_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
